In [133]:
import numpy as np
import pandas as pd

In [134]:
np.__version__

'1.24.3'

In [164]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

u.dot(v)

14

In [165]:
np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
]) @ v

array([14,  5,  5])

In [177]:
np.array([
    [1,2,3],
    [4,5,6],
]) @ np.array([
    [7,8],
    [9,10],
    [11,12]
])

array([[ 58,  64],
       [139, 154]])

In [136]:
# !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

In [137]:
pd.read_csv('./housing.csv')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [138]:
df = pd.read_csv('./housing.csv')

In [208]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [140]:
missing_counts = missing_values.sum()

In [141]:
df['ocean_proximity'].nunique()

5

In [142]:
near_bay = df[df['ocean_proximity'] == 'NEAR BAY']
near_bay['median_house_value'].mean()

259212.31179039303

In [143]:
df['total_bedrooms'].mean()

537.8705525375618

In [144]:
df['total_bedrooms'].fillna(0).mean()

532.47621124031

In [195]:
islands_df = df[df['ocean_proximity'] == 'ISLAND']
# islands_df = islands_df.fillna(0)
islands_df = islands_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
# islands_df = islands_df.drop_duplicates()
islands_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [196]:
X = islands_df.to_numpy()
XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [197]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [198]:
y = np.array([950, 1300, 800, 1000, 1300])

In [200]:
w = (XTX_inv @ X.T) @ y
w

array([23.12330961, -1.48124183,  5.69922946])

In [193]:
np.linalg.inv(np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8],
]))

array([[ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15],
       [-3.4313140e+15,  8.5782850e+15, -5.1469710e+15],
       [ 1.7156570e+15, -4.2891425e+15,  2.5734855e+15]])