In [7]:
import numpy as np
import pandas as pd

In [8]:
# QUESTION 1

pd.__version__

'1.5.3'

In [136]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

In [19]:
df = pd.read_csv('./housing.csv')

In [32]:
# QUESTION 2
len(df.columns)

10

In [33]:
# QUESTION 3

df.isnull().sum()


longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [43]:
# QUESTION 4
df.nunique()


longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [37]:
# QUESTION 5
near_bay = df[df['ocean_proximity'] == 'NEAR BAY']
near_bay['median_house_value'].mean()

259212.31179039303

In [40]:
# QUESTION 6
df['total_bedrooms'].mean()
df['total_bedrooms'].fillna(537.8705525375618).mean()

537.8705525375617

In [42]:
# QUESTION 7

islands_df = df[df['ocean_proximity'] == 'ISLAND']
islands_df = islands_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]
islands_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [196]:
X = islands_df.to_numpy()
XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [197]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [198]:
y = np.array([950, 1300, 800, 1000, 1300])

In [200]:
w = (XTX_inv @ X.T) @ y
w

array([23.12330961, -1.48124183,  5.69922946])